# Azure Pipelines YAML configuration file to build a React Native Android app
trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  androidSdkVersion: '30'
  buildDir: 'android/app/build/outputs/apk'

steps:

# Step 1: Install Node.js
- task: UseNode@1
  displayName: 'Use Node.js 16.x'

# Step 2: Install dependencies
- script: |
    npm install
    npm install -g react-native-cli
  displayName: 'Install dependencies'

# Step 3: Install Android dependencies
- script: |
    yes | sdkmanager --licenses
    sdkmanager "build-tools;${{ variables.androidSdkVersion }}.0.0" "platforms;android-${{ variables.androidSdkVersion }}"
  displayName: 'Install Android SDK dependencies'

# Step 4: Build the Android app
- script: |
    cd android
    ./gradlew assembleRelease
  displayName: 'Build Android APK'

# Step 5: Publish the APK as a pipeline artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/${{ variables.buildDir }}'
    artifactName: 'android-apk'
    publishLocation: 'pipeline'
  displayName: 'Publish APK artifact'
