#PREDIF
ROUTE_TO_ANDROID_VERSIONS_FILE=android/app/build.gradle;
ROUTE_TO_IOS_VERSIONS_FILE=ios/Shkolo.xcodeproj/project.pbxproj;

#IOS UPDATE VERSIONS
PROJECT_VERSION=$(grep -m 1 "CURRENT_PROJECT_VERSION = [[:digit:]]*" $ROUTE_TO_IOS_VERSIONS_FILE);
PROJECT_VERSION=$(grep -Eo '[0-9]{1,100}' <<< $PROJECT_VERSION);
PROJECT_VERSION=$((PROJECT_VERSION+1));
PROJECT_VERSION="CURRENT_PROJECT_VERSION = $PROJECT_VERSION";

MARKETING_VERSION=$(grep -m 1 "MARKETING_VERSION = [[:digit:]]*.[[:digit:]]*.[[:digit:]]*" $ROUTE_TO_IOS_VERSIONS_FILE);
MARKETING_VERSION=$(grep -Eo "[0-9]{1,100}.[0-9]{1,100}.[0-9]{1,100}" <<< $MARKETING_VERSION);

IOS_FIRST_NUMBER=$(grep -Eo '^[[:digit:]]{1,100}' <<< $MARKETING_VERSION);
IOS_FIRST_NUMBER=$(grep -Eo '[[:digit:]]{1,100}' <<< $IOS_FIRST_NUMBER);

IOS_MIDDLE_NUMBER=$(grep -Eo '.[[:digit:]]{1,100}.' <<< $MARKETING_VERSION);
IOS_MIDDLE_NUMBER=$(grep -Eo '[[:digit:]]{1,100}' <<< $IOS_MIDDLE_NUMBER);

IOS_LAST_NUMBER=$(grep -Eo '[0-9]+$' <<< $MARKETING_VERSION);
IOS_LAST_NUMBER=$((IOS_LAST_NUMBER+1));


if [[ $IOS_LAST_NUMBER == 10 ]]; then
IOS_LAST_NUMBER=0;
IOS_MIDDLE_NUMBER=$((IOS_MIDDLE_NUMBER+1));
fi

MARKETING_VERSION="MARKETING_VERSION = $IOS_FIRST_NUMBER.$IOS_MIDDLE_NUMBER.$IOS_LAST_NUMBER;";

#ANDROID UPDATE VERSIONS
VERSION_CODE=$(grep "versionCode [[:digit:]]*$" $ROUTE_TO_ANDROID_VERSIONS_FILE);
VERSION_CODE=$(grep -Eo '[0-9]{1,100}' <<< $VERSION_CODE);
VERSION_CODE=$((VERSION_CODE+1));
VERSION_CODE="versionCode $VERSION_CODE";

VERSION_NAME=$(grep "versionName \"[[:digit:]]*" $ROUTE_TO_ANDROID_VERSIONS_FILE);
VERSION_NAME=$(grep -Eo "[0-9]{1,100}.[0-9]{1,100}.[0-9]{1,100}" <<< $VERSION_NAME);

ANDROID_FIRST_NUMBER=$(grep -Eo '^[[:digit:]]{1,100}' <<< $VERSION_NAME);
ANDROID_FIRST_NUMBER=$(grep -Eo '[[:digit:]]{1,100}' <<< $ANDROID_FIRST_NUMBER);

ANDROID_MIDDLE_NUMBER=$(grep -Eo '.[[:digit:]]{1,100}.' <<< $VERSION_NAME);
ANDROID_MIDDLE_NUMBER=$(grep -Eo '[[:digit:]]{1,100}' <<< $ANDROID_MIDDLE_NUMBER);

ANDROID_LAST_NUMBER=$(grep -Eo '[0-9]+$' <<< $VERSION_NAME);
ANDROID_LAST_NUMBER=$((ANDROID_LAST_NUMBER+1));

if [[ $ANDROID_LAST_NUMBER == 10 ]]; then
ANDROID_LAST_NUMBER=0;
ANDROID_MIDDLE_NUMBER=$((ANDROID_MIDDLE_NUMBER+1));
fi

VERSION_NAME="versionName \"$ANDROID_FIRST_NUMBER.$ANDROID_MIDDLE_NUMBER.$ANDROID_LAST_NUMBER\""

#IOS SET NEW VERSIONS
sed -i "s/CURRENT_PROJECT_VERSION = [[:digit:]]*/${PROJECT_VERSION}/g" $ROUTE_TO_IOS_VERSIONS_FILE;
sed -i "s/MARKETING_VERSION = [[:digit:]]*.[[:digit:]]*.[[:digit:]]*;/${MARKETING_VERSION}/g" $ROUTE_TO_IOS_VERSIONS_FILE;

#ANDROID SET NEW VERSIONS
sed -i "s/versionCode [[:digit:]]*$/${VERSION_CODE}/g" $ROUTE_TO_ANDROID_VERSIONS_FILE;
sed -i "s/versionName \"[[:digit:]]*.[[:digit:]]*.[[:digit:]]*\"/${VERSION_NAME}/g" $ROUTE_TO_ANDROID_VERSIONS_FILE;
