version: '2.1'
orbs:
  rn: react-native-community/react-native@8.0.1
jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm install
          name: Install
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  fastlane_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm install
          name: Install
      - run:
          command: bundle exec fastlane android release
          name: Run Fastlane
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - rn/android_build:
          build_type: release
          requires:
            - analyse_js
      - rn/android_test:
          requires:
            - rn/android_build
      - fastlane_release:
          requires:
            - rn/android_test
