version: 2.1

jobs:
  build:
    docker:
      - image: getmoona/react-native-circleci:latest # For Android tools, use a specific image

    steps:
      # Checkout code
      - checkout

      # Install Node.js and npm dependencies
      - run:
          name: Install Node.js and NPM dependencies
          command: |
            npm install
      # Build the Android APK
      - run:
          name: Build Android APK
          command: |
            cd android
            ./gradlew assembleRelease

workflows:
  version: 2
  build:
    jobs:
      - build
