version: 2.1

orbs:
  android: circleci/android@2.4.0  # Optional for Android-specific commands

jobs:
  build:
    docker:
      - image: circleci/android:api-29-node8-alpha # For Android tools, use a specific image

    steps:
      # Checkout code
      - checkout

      # Install Node.js and npm dependencies
      - run:
          name: Install Node.js and NPM dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
            npm install
      # Build the Android APK
      - run:
          name: Build Android APK
          command: |
            cd android
            ./gradlew assembleRelease

workflows:
  version: 2
  build:
    jobs:
      - build
