version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30 # For Android tools, use a specific image

    steps:
      # Checkout code
      - checkout

      # Install Node.js and npm dependencies
      - run:
          name: Install Node.js and NPM dependencies
          command: |
            curl -fsSL https://deb.nodesource.com/setup_20.x
            apt-get install -y nodejs
            npm install -g npm
            npm install
      # Build the Android APK
      - run:
          name: Build Android APK
          command: |
            cd android
            ./gradlew assembleRelease

workflows:
  version: 2
  build:
    jobs:
      - build
