version: 2.1

orbs:
  android: circleci/android@2.4.0  # Optional for Android-specific commands

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Use Python image (could also use Node.js image)
      - image: circleci/android:api-30  # For Android tools, use a specific image

    steps:
      # Checkout code
      - checkout

      # Install Node.js and npm dependencies
      - run:
          name: Install Node.js and NPM dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
            npm install

      # Install Android SDK (if needed) and other Android dependencies
      - run:
          name: Install Android SDK dependencies
          command: |
            echo y | sdkmanager --licenses
            sdkmanager "platforms;android-30" "build-tools;30.0.3"

      # Build the Android APK
      - run:
          name: Build Android APK
          command: |
            cd android
            ./gradlew assembleRelease

workflows:
  version: 2
  build:
    jobs:
      - build
