version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build:
    docker:
      - image: circleci/android:latest
    steps:
      - checkout
      - run: echo "$KEYSTORE_BASE64" | base64 --decode > ./my-release-key.jks
      - run: chmod 600 ./my-release-key.jks
      - run: ./gradlew assembleRelease
