version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:@2.4.0
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: Decode Keystore
          command: |
            echo "$KEYSTORE_BASE64" | base64 --decode > ./my-release-key.jks
      - run:
          name: Set Permissions
          command: chmod 600 ./my-release-key.jks
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease
