version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android::2025.01.1-node    # For Android tools, use a specific image

    steps:
      # Checkout code
      - checkout

      # Install Node.js, npm dependencies, and Java 17
      - run:
          name: Install Node.js, npm dependencies, and Java 17
          command: |
            npm install

      - run:
          name: Build Android APK
          command: |
            cd android
            ./gradlew assembleRelease

workflows:
  version: 2
  build:
    jobs:
      - build
